artifacts_root: ./artifacts

data_ingestion:
  root_dir: ./artifacts/data_ingestion
  source_URL: https://github.com/AmineMekki01/data/raw/main/brain_image_classification.zip
  local_data_file: ./artifacts/data_ingestion/brain_image_classification.zip
  unzip_dir: ./artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model_path.pth
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.pth


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.pth


training:
  root_dir: artifacts/Training
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.pth
  trained_model_path: artifacts/Training/final_model.pth
  score_path: artifacts/scoring/Training

evaluation:
  trained_model_path: artifacts/Training/final_model.pth
  score_path: artifacts/scoring/Evaluation
  evaluation_data: artifacts/data_ingestion/brain_image_classification/brain_mri_images/Testing

inference:
  root_dir: artifacts/inference
  trained_model_path: artifacts/Training/final_model.pth
  images_dir: artifacts/data_ingestion/brain_image_classification/Prediction check images/Prediction check images/Prediction check images
