artifacts_root: ./artifacts

data_ingestion:
  root_dir: ./artifacts/data_ingestion
  source_URL: https://github.com/AmineMekki01/data/raw/main/brain_image_classification.zip
  local_data_file: ./artifacts/data_ingestion/brain_image_classification.zip
  unzip_dir: ./artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
